# Generated by Django 4.2.27 on 2026-01-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_type', models.CharField(choices=[('BOT', 'Бот'), ('STUDENT', 'Студент')], max_length=10, verbose_name='Тип противника')),
                ('bot_level', models.CharField(blank=True, choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, null=True, verbose_name='Уровень бота')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В процессе'), ('FINISHED', 'Завершена'), ('ABANDONED', 'Прервана')], default='IN_PROGRESS', max_length=15, verbose_name='Статус')),
                ('result', models.CharField(blank=True, choices=[('WIN', 'Победа'), ('LOSE', 'Поражение'), ('DRAW', 'Ничья')], max_length=4, null=True, verbose_name='Результат')),
                ('coins_earned', models.IntegerField(default=0, verbose_name='Заработано монет')),
                ('fen_position', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100, verbose_name='Позиция (FEN)')),
                ('last_move', models.CharField(blank=True, max_length=10, verbose_name='Последний ход')),
                ('current_turn', models.CharField(default='white', max_length=5, verbose_name='Чей ход')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_chess_games', to=settings.AUTH_USER_MODEL, verbose_name='Противник')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_chess_games', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_chess_games', to=settings.AUTH_USER_MODEL, verbose_name='Белые')),
            ],
            options={
                'verbose_name': 'Шахматная партия',
                'verbose_name_plural': 'Шахматные партии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chessgamehistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'Шахматная игра (ручная)', 'verbose_name_plural': 'Шахматные игры (ручные)'},
        ),
        migrations.CreateModel(
            name='ChessInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено'), ('EXPIRED', 'Истекло')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chess_invites', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite', to='api.chessgame', verbose_name='Игра')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chess_invites', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Приглашение в шахматы',
                'verbose_name_plural': 'Приглашения в шахматы',
                'ordering': ['-created_at'],
            },
        ),
    ]
