# Generated by Django 4.2.27 on 2026-01-28 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_user_raw_password_shoppurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='shoppurchase',
            name='product_code',
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='purchase_code',
            field=models.CharField(default=api.models.generate_purchase_code, max_length=20, unique=True, verbose_name='Код покупки'),
        ),
    ]
