# Generated by Django 4.2.27 on 2026-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_shop_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='shoppurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Можно забрать'), ('SOLD', 'Получено'), ('RETURNED', 'Возвращено')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
    ]
